### ISSUE TITLE
Not working after the latest Figma update.

### ISSUE THREAD

**Issue by elcicneha** [resul-celik/r32d23w#1]
I use the plugin all the time, I work with a lot of documents, book designs in Figma, thus this is a huge life saver. 

Last I used this was about a month ago. In between Figma has launched a massive update. I'm not sure if it's the update that's causing the problem, but whenever I click the button, I see the toast message that it's paginating, but it doesn't work, no page numbers are added. You can check out the recording attached below (sorry about the quality, had to compress it to upload)

https://github.com/user-attachments/assets/0ea60746-0974-423b-9a35-06132d586002

**Comment by resul-celik** [comment]
hi @elcicneha I'm working on it, and I'll solve this issue as soon as possible. Thank you for letting me know.

**Comment by elcicneha** [comment]
Awesome, thanks. <3

**Comment by resul-celik** [comment]
Hi, @elcicneha I've fixed this issue. If you have any problem, please let me know.

**Comment by elcicneha** [comment]
It's working perfectly. Thanks a lot.
